desarrollo/src/portal/portal/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include, patterns
#from django.views.generic.base import RedirectView

from django.views.generic.base import TemplateView
from products.sitemaps import ProductSitemap
from products.models import Product
from django.views.generic.list import ListView


#from portal.products.models import PortalProfile
#from django.views.generic import ListView
admin.autodiscover()
handler500 = 'django.views.defaults.server_error'
handler404 = 'django.views.defaults.page_not_found'
handler403 = 'django.views.defaults.permission_denied'

sitemaps = {
    'Products': ProductSitemap
}
urlpatterns = patterns('',
    #    Examples:
    #url(r'^$', 'portal.views.home', name='home'),
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^home\.html$', 'products.views.home_view', {'template_name':"home.html"}),
    url(r'^about\.html$', TemplateView.as_view(template_name="about.html")),
    
    url(r'^services\.html$', TemplateView.as_view(template_name="services/index.html")),
    url(r'^services/openerp\.html$', TemplateView.as_view(template_name="services/openerp.html")),
    url(r'^services/consultoria_empresarial\.html$', TemplateView.as_view(template_name="services/consultoria_empresarial.html")),
    url(r'^services/desarrollo_software\.html$', TemplateView.as_view(template_name="services/desarrollo_software.html")),
    url(r'^services/traduccion_subtitulado\.html$', TemplateView.as_view(template_name="services/traduccion_subtitulado.html")),
    url(r'^services/migracion\.html$', TemplateView.as_view(template_name="services/migracion.html")),
    url(r'^services/capacitacion\.html$', TemplateView.as_view(template_name="services/capacitacion.html")),
    url(r'^services/paq-teorico\.html$', TemplateView.as_view(template_name="services/paq-teorico.html")),
    url(r'^services/paq-tecnologico\.html$', TemplateView.as_view(template_name="services/paq-tecnologico.html")),
    url(r'^services/paq-infraestructura\.html$', TemplateView.as_view(template_name="services/paq-infraestructura.html")),
    url(r'^services/identidad_diseno_posicionamiento\.html$', TemplateView.as_view(template_name="services/identidad_diseno_posicionamiento.html")),
    url(r'^contact\.html$', 'products.views.contact_view', {'template_name':"contact.html"}),
    
    url(r'', include('products.urls')),
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/profile/$', TemplateView.as_view(template_name='accounts/profile.html')),
    url(r'^accounts/login_required\.html$', TemplateView.as_view(template_name='accounts/login_required.html')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^profiles/', include('profiles.urls')),
    
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.index', {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^xmlrpc/$', 'django_xmlrpc.views.handle_xmlrpc', name='xmlrpc'),
    
    url(r'^offline/', include('paypal.standard.ipn.urls')),
    url(r'^support/', include('live_support.urls')),
)

urlpatterns += patterns('',
    url(r'^403/$', 'django.views.defaults.permission_denied'),
    url(r'^404/$', 'django.views.defaults.page_not_found'),
#    url(r'^500/$', 'django.views.defaults.server_error'),
)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT})
    )

desarrollo/src/portal/profiles/urls.py
"""
URLConf for Django user profile management.

Recommended usage is to use a call to ``include()`` in your project's
root URLConf to include this URLConf for any URL beginning with
'/profiles/'.

If the default behavior of the profile views is acceptable to you,
simply use a line like this in your root URLConf to set up the default
URLs for profiles::

    (r'^profiles/', include('profiles.urls')),

But if you'd like to customize the behavior (e.g., by passing extra
arguments to the various views) or split up the URLs, feel free to set
up your own URL patterns for these views instead. If you do, it's a
good idea to keep the name ``profiles_profile_detail`` for the pattern
which points to the ``profile_detail`` view, since several views use
``reverse()`` with that name to generate a default post-submission
redirect. If you don't use that name, remember to explicitly pass
``success_url`` to those views.

"""

from django.conf.urls import patterns, url, include

from profiles import views


urlpatterns = patterns('',
                       url(r'^create/$',
                           views.create_profile,
                           name='profiles_create_profile'),
                       url(r'^edit/$',
                           views.edit_profile,
                           name='profiles_edit_profile'),
                       url(r'^(?P<username>\w+)/$',
                           views.profile_detail,
                           name='profiles_profile_detail'),
                       url(r'^$',
                           views.profile_list,
                           name='profiles_profile_list'),
                       )

desarrollo/src/portal/social_bookmarking/test_project/urls.py
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/(.*)', admin.site.root),    

    (r'^', include('test_app.urls')),



)

desarrollo/src/portal/live_support/models.py
from datetime import datetime
from uuid import uuid4
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.core.cache import cache


class SupportGroup(models.Model):
    name = models.CharField(_("name"), max_length=255)
    agents = models.ManyToManyField(User, blank=True, related_name='agent_support_groups')
    supervisors = models.ManyToManyField(User, blank=True, related_name='supervisor_support_groups')

    def __unicode__(self):
        return self.name


class ChatManager(models.Manager):
    def get_query_set(self):
        return super(ChatManager, self).get_query_set().filter(ended=None)


class Chat(models.Model):
    name = models.CharField(_("name"), max_length=255)
    hash_key = models.CharField(unique=True, max_length=64, null=True,
                                editable=False, blank=True, default=uuid4)
    details = models.TextField(_("question"), blank=True)
    started = models.DateTimeField(auto_now_add=True)
    ended = models.DateTimeField(null=True, blank=True)
    agents = models.ManyToManyField(User, blank=True, related_name='chats')
    objects = models.Manager()
    active = ChatManager()
    support_group = models.ForeignKey(SupportGroup, null=True, blank=True)

    def __unicode__(self):
        return '%s: %s' % (self.started, self.name)

    def end(self):
        self.ended = datetime.now()
        self.save()

    def is_active(self):
        return cache.get('chat_%s' % self.id, 'inactive')

    class Meta:
            permissions = (
                ("chat_admin", "Chat Admin"),
            )


class ChatMessage(models.Model):
    chat = models.ForeignKey(Chat, related_name='messages')
    name = models.CharField(max_length=255, blank=True)
    agent = models.ForeignKey(User, blank=True, null=True)
    message = models.TextField()
    sent = models.DateTimeField(auto_now_add=True)

    def get_name(self):
        if self.agent:
            return self.agent.first_name or self.agent.username
        else:
            return self.name

    def __unicode__(self):
        return '%s: %s' % (self.sent, self.message)

desarrollo/src/portal/paypal/pro/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms

from paypal.pro.fields import CreditCardField, CreditCardExpiryField, CreditCardCVV2Field, CountryField
from paypal.pro.exceptions import PayPalFailure

class PaymentForm(forms.Form):
    """Form used to process direct payments."""
    firstname = forms.CharField(255, label="First Name")
    lastname = forms.CharField(255, label="Last Name")
    street = forms.CharField(255, label="Street Address")
    city = forms.CharField(255, label="City")
    state = forms.CharField(255, label="State")
    countrycode = CountryField(label="Country", initial="US")
    zip = forms.CharField(32, label="Postal / Zip Code")
    acct = CreditCardField(label="Credit Card Number")
    expdate = CreditCardExpiryField(label="Expiration Date")
    cvv2 = CreditCardCVV2Field(label="Card Security Code")

    def process(self, request, item):
        """Process a PayPal direct payment."""
        from paypal.pro.helpers import PayPalWPP
        wpp = PayPalWPP(request) 
        params = self.cleaned_data
        params['creditcardtype'] = self.fields['acct'].card_type
        params['expdate'] = self.cleaned_data['expdate'].strftime("%m%Y")
        params['ipaddress'] = request.META.get("REMOTE_ADDR", "")
        params.update(item)

        try:
            # Create single payment:
            if 'billingperiod' not in params:
                nvp_obj = wpp.doDirectPayment(params)
            # Create recurring payment:
            else:
                nvp_obj = wpp.createRecurringPaymentsProfile(params, direct=True)
        except PayPalFailure:
            return False
        return True

class ConfirmForm(forms.Form):
    """Hidden form used by ExpressPay flow to keep track of payer information."""
    token = forms.CharField(max_length=255, widget=forms.HiddenInput())
    PayerID = forms.CharField(max_length=255, widget=forms.HiddenInput())

desarrollo/src/portal/products/forms.py
import os
import urllib2
import xmlrpclib
import cookielib
import datetime
from dateutil.relativedelta import relativedelta

from django import forms
from django.forms.util import ErrorList
from django.forms.models import ModelForm
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.template import loader
from django.core.mail import send_mail

from registration.forms import RegistrationFormUniqueEmail
from products.models import Product, ProductPlan, ProductContract, ProductContractInstance, ProductContractInstanceUser

from config import portal_config
from django.utils.crypto import get_random_string
from django.core.mail.message import EmailMultiAlternatives

attrs_dict = { 'class': 'required' }
login_conn = xmlrpclib.ServerProxy(settings.URL_OPENERP + '/xmlrpc/common')
db_conn = xmlrpclib.ServerProxy(settings.URL_OPENERP + '/xmlrpc/db')
obj_conn = xmlrpclib.ServerProxy(settings.URL_OPENERP + '/xmlrpc/object')

class PortalRegistrationForm(RegistrationFormUniqueEmail):
    first_name = forms.CharField(widget=forms.TextInput(attrs=attrs_dict))
    last_name = forms.CharField(widget=forms.TextInput(attrs=attrs_dict))
    country = forms.CharField(widget=forms.TextInput(attrs=attrs_dict))
    phone = forms.CharField(widget=forms.TextInput(attrs=attrs_dict))



class ProductBuyForm(forms.Form):
    plan = forms.IntegerField()
    product = forms.IntegerField()

#    def clean_product(self):
#        product = Product.objects.filter(id=self.cleaned_data['product'])
#        if product:
#            return product
#        raise forms.ValidationError(_("El producto no es valido."))

    def clean_plan(self):
        prod = Product.objects.filter(id=self.cleaned_data['product'])
        plan = ProductPlan.objects.filter(id=self.cleaned_data['plan'])
        if plan and self.cleaned_data['plan'] in prod.plans:
            return plan
        raise forms.ValidationError(_("El plan no es valido."))



class ProductContractForm(forms.Form):
    contract = forms.IntegerField()
    demo = forms.BooleanField()

    def clean_contract(self):
        contract = ProductContract.objects.get(id=self.cleaned_data['contract'])
        if contract:
            return contract
        raise forms.ValidationError(_("El Contrato no es valido."))

    def save(self):
        contract = self.cleaned_data["contract"]
        if contract.state == 'draft' or contract.state == 'demo':

            filename = str(contract.product.backup)
            data = open(os.path.join(settings.MEDIA_ROOT, filename), mode='rb').read().encode('base64')
            instances = contract.instances.all()
            if self.data["demo"] and contract.state != 'demo':
                instances = [instances[0]]
                contract.state = 'demo'
                today = datetime.datetime.today()
                contract.init_date = today
                contract.end_date = today + relativedelta(months=contract.product.demo_end)
            else:
                contract.state = 'active'
                contract.init_date = datetime.datetime.today()
                contract.end_date = datetime.datetime.today() + relativedelta(months=contract.months)
            for instance in instances:
                #admin_group_names = [grp.strip() for grp in contract.product.admin_groups.strip().split(',')]
                #user_group_names = [grp.strip() for grp in contract.product.user_groups.strip().split(',')]
                #admin_group_ids = obj_conn.execute(instance.db_name, uid, settings.OPENERP_ADMIN_PASSWORD, 'res.groups', 'search', [('name', 'in', admin_group_names)])
                #user_group_ids = obj_conn.execute(instance.db_name, uid, settings.OPENERP_ADMIN_PASSWORD, 'res.groups', 'search', [('name', 'in', user_group_names)])

                if instance.state == 'demo':
                    uid = login_conn.login(instance.db_name, 'admin', settings.OPENERP_ADMIN_PASSWORD)
                    instance.state = contract.state
                    if not contract.profile.pay_excent:
                        stop_data = {
                            'contract_id': contract.id,
                            'end_date': datetime.datetime.strftime(contract.end_date, '%Y-%m-%d %H:%M:%S')
                        }
                        obj_conn.execute(instance.db_name, uid, settings.OPENERP_ADMIN_PASSWORD, 'eloq.contract_stop', 'write', instance.stop_id, stop_data)
                else:
                    user_ids = []
    #creacion de la instancia en openerp
                    db_conn.restore(settings.OPENERP_ADMIN_PASSWORD, instance.db_name, data)
                    uid = login_conn.login(instance.db_name, 'admin', settings.OPENERP_ADMIN_PASSWORD)
                    users = instance.users.all()
                    for no_user in users:
                        no_user.password = get_random_string()
                        groups = [6,0]

#                        if no_user.app_admin:
#                            groups.append(admin_group_ids)
#                        else:
#                            groups.append(user_group_ids)
                        user_data = {
                            'name': no_user.username,
                            'login': no_user.username,
                            'new_password': no_user.password,
                            'user_email': contract.profile.user.email,
                            #'groups_id': groups
                        }
                        no_user.user_id = obj_conn.execute(instance.db_name, uid, settings.OPENERP_ADMIN_PASSWORD, 'res.users', 'create', user_data)
                        no_user.state = 'active'
                        no_user.save()
                        user_ids.append(no_user.user_id)
                    instance.state = contract.state
                    if not contract.profile.pay_excent:
                        module_ids = obj_conn.execute(instance.db_name, uid, settings.OPENERP_ADMIN_PASSWORD, 'ir.module.module', 'search', [('name', '=', 'eloq_portal')])
                        obj_conn.execute(instance.db_name, uid, settings.OPENERP_ADMIN_PASSWORD, 'ir.module.module', 'button_immediate_install', module_ids)
    #creacion de la tarea de vencimiento de contrato
                        stop_data = {
                            'name': instance.db_name,
                            'contract_id': contract.id,
                            'end_date': datetime.datetime.strftime(contract.end_date, '%Y-%m-%d %H:%M:%S'),
                            'user_ids': [(6, 0, user_ids)],
                            'interval': contract.months,
                            'state': contract.state
                        }
                        instance.stop_id = obj_conn.execute(instance.db_name, uid, settings.OPENERP_ADMIN_PASSWORD, 'eloq.contract_stop', 'create', stop_data)
                instance.save()
            c = {'contract': contract,'url_openerp': settings.URL_OPENERP,}
            subject = loader.render_to_string(portal_config.get('create').get('subject_template'), c)
            subject = ''.join(subject.splitlines())
            message = loader.render_to_string(portal_config.get('create').get('email_template'), c)
            msg = EmailMultiAlternatives(subject, message, None, [contract.profile.user.email])
            msg.attach_alternative(message, "text/html")
            msg.send(True)
#             send_mail(subject, message, None, [contract.profile.user.email],fail_silently=True)
        contract.save()



class ProductShareForm(forms.Form):
    product = forms.IntegerField()
    email = forms.EmailField()

    def clean_product(self):
        product = Product.objects.get(id=self.cleaned_data['product'])
        if product:
            return product
        raise forms.ValidationError(_("El producto no es valido."))

desarrollo/src/portal/portal/templates/profiles/create_profile.html
<script>
 $(document).ready(function() {
   $("#profile").addClass("active");
 });
</script>

<div class="description">
    <h2>Create Profile:</h2>
</div>

 
<h2>{{ user|capfirst }}, before we begin, lets set some of your account preferences. These can be changed at any time.</h2>
 
<form method="POST" action="">
        <p>
            Default League to bet: <span class="required">*</span>  {{ form.pref_sport }}
            {% for error in form.pref_sport.errors %}
                {{ error|escape }}
            {% endfor %}
        </p>

        <p>
            Default Number of games to bet: <span class="required">*</span>  {{ form.pref_num_games }}
            {% for error in form.pref_num_games.errors %}
                {{ error|escape }}
            {% endfor %}
        </p>
	{% csrf_token %}
    <input type="submit" name="submit" class="submit" value="Create Profile">
</form>
 

desarrollo/src/portal/portal/templates/profiles/edit_profile.html
{% load l10n %}
{% load expr %}
<div>
	<ul class="breadcrumb">
	    <li><a href="/profiles/{{ user }}/">Perfil</a><span class="divider">/</span></li>
	    <li class="active"><a href="/profiles/edit/">Actualizar Datos</a></li>
    </ul>
	<div class="well">
		<form method="POST" action="/profiles/edit/" id="profile_form" title="Cambiar Mi Perfil">
		{% csrf_token %}
			<table>
				<tr>
					<td>
						<table>
							<tr>
								<td><label for="id_name">Nombre:</label></td>
								<td><input class="required" id="id_first_name" value="{{ user.first_name }}" name="first_name" type="text" /></td></tr>
							<tr>
							<tr>
								<td><label for="id_username">Nombre de Usuario:</label></td> 
								<td><input id="id_username" maxlength="30" value="{{ user.username }}" name="username" type="text" require="true" label="Nombre de Usuario" /></td>
							</tr>
							<tr>
								<td><label for="id_email">Correo Electr&oacute;nico:</label></td> 
								<td><input id="id_email" name="email" value="{{ user.email }}" type="text" validate="email" require="true" label="E-mail" /></td>
							</tr>
						</table>
					</td>
					<td>
						<div style="border-left: 1px solid #EEEEEE; padding: 0 15px">
							<table>
								<tr>
									<td><label for="id_lastname">Apellidos:</label></td>
									<td><input class="required" id="id_last_name" name="last_name" value="{{ user.last_name }}" type="text" /></td>
								</tr>
								<tr>
									<td><label for="id_country">Pa&iacute;s:</label></td>
									<td>
										<select class="required" id="id_country" name="country" style="width: 220px; margin-bottom:10px;">
										{% for country in countries %}
											 <option value="{% expr country[0] as sig %}{{ sig }}" {% if profile.country == sig %}selected="selected"{% endif %}>{% expr country[1] as county %}{{ county|localize}}</option>
										{% endfor %} 
										</select>
									</td>
								</tr>
								<tr>
									<td><label for="id_phone">Tel&eacute;fono:</label></td>
									<td><input class="required" id="id_phone" name="phone" value="{{ profile.phone }}" type="text" /></td>
								</tr>
							</table>
						</div>
					</td>
				</tr>
			</table>
		    <input type="submit" name="submit" class="submit btn btn-primary" value="Aceptar">
		    <input type="button" value="Cancelar" id="cancel_button" class="btn btn-success"/>
		</form>
	</div>
	<script type="text/javascript">
		$('#profile_form').submit(function(){
			$.ajax({
				type: 'post',
				url: $('#profile_form').attr('action'),
				data: $('#profile_form').serialize(),
				success: function(response) {
					History.pushState({state:null}, null, "/accounts/profile/");
				}
			});
			return false;
		});
		$('#cancel_button').click(function(){
			History.pushState({state:null}, null, "/profiles/{{ user }}/");
			return false;
		});
		function format(country) {
            if (!country.id) return country.text; // optgroup
            return "<img class='flag' src='{{ STATIC_URL }}flags/" + country.id.toLowerCase() + ".gif'/>&nbsp;" + country.text;
        }
        $("#id_country").select2({
            formatResult: format,
            formatSelection: format,
            escapeMarkup: function(m) { return m; }
        });

        $('ul.breadcrumb li a').click(function(e) {
			History.pushState({state:this}, null, this.href);
			return false;
		});
	</script>
<div>

desarrollo/src/portal/portal/templates/profiles/password_change.html
<div>
	<ul class="breadcrumb">
	    <li><a href="/profiles/{{ user }}/">Perfil</a><span class="divider">/</span></li>
	    <li class="active"><a href="/profiles/password/change/">Cambiar Contrase&ntilde;a</a></li>
    </ul>
	<div class="well">
		<form action="/profiles/password/change/" method="post" id="password_form" title="Cambiar Contrase&ntilde;a">
		{% csrf_token %}
		{{ form.errors }}
			<table>
				<tr>
					<th>
						<label for="id_old_password">Contrase&ntilde;a anterior:</label>
					</th>
					<td>
						<input id="id_old_password" name="old_password" type="password" />
					</td>
				</tr>
				<tr>
					<th>
						<label for="id_new_password1">Nueva contrase&ntilde;a:</label>
					</th>
					<td>
						<input id="id_new_password1" name="new_password1" type="password" />
					</td>
				</tr>
				<tr>
					<th>
						<label for="id_new_password2">Confirme la nueva contrase&ntilde;a :</label>
					</th>
					<td>
						<input id="id_new_password2" name="new_password2" type="password" />
					</td>
				</tr>
			</table>
			<input type="submit" value="Aceptar" class="btn btn-primary"/>
			<input type="button" value="Cancelar" id="cancel_button" class="btn btn-success"/>
		</form>
	</div>
	<script type="text/javascript">
		$('#password_form').submit(function(){
			$.ajax({
				type: 'post',
				url: $('#password_form').attr('action'),
				data: $('#password_form').serialize(),
				success: function(response) {
					$('.center_content').html(response);
					$('#login_container').load("/accounts/login/");
				}
			});
			return false;
		});
		$('#cancel_button').click(function(){
			History.pushState({state:null}, null, "/profiles/{{ user }}/");
			return false;
		});
		$('ul.breadcrumb li a').click(function(e) {
			History.pushState({state:this}, null, this.href);
			return false;
		});
	</script>
</div>

desarrollo/src/portal/portal/templates/profiles/password_reset.html
	<div class="well">
		<form action="/profiles/password/reset/" method="post" id="reset_form">
			{% csrf_token %}
			<h1>Recuperar Contrase&ntilde;a</h1>
			<p>Olvido su Contrase&ntilde;a? Introduzca debajo su direcci&oacute;n de correo electr&oacute;nico y le enviaremos las instrucciones para obtener una nueva.</p>
			<label for="id_email">Correo electr&oacute;nico:</label> 
			<input id="id_email" maxlength="254" name="email" type="text" /> 
			<input type="submit" value="Aceptar" class="btn btn-primary"/>
			<input type="button" value="Cancelar" id="cancel_button" class="btn btn-success"/>
		</form>
	</div>
	<script type="text/javascript">
		$('#reset_form').submit(function(){
			$.ajax({
				type: 'post',
				url: $('#reset_form').attr('action'),
				data: $('#reset_form').serialize(),
				success: function(response) {
					History.pushState({state:null}, null, "/accounts/profile/");
				}
			});
			return false;
		});
		$('#cancel_button').click(function(){
			History.pushState({state:null}, null, "/home.html");
			return false;
		});
	</script>
    

desarrollo/src/portal/portal/templates/profiles/profile_list.html
{% extends "main_template.html" %}
{% block content%}

<script>
 $(document).ready(function() {
   $("#profile").addClass("active");
 });
</script>

<div class="description">
    <h2>Profile Details:</h2>
</div>
 
Add here
 
{% endblock %}