desarrollo/src/portal/portal/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include, patterns
#from django.views.generic.base import RedirectView

from django.views.generic.base import TemplateView
from products.sitemaps import ProductSitemap
from products.models import Product
from django.views.generic.list import ListView


#from portal.products.models import PortalProfile
#from django.views.generic import ListView
admin.autodiscover()
handler500 = 'django.views.defaults.server_error'
handler404 = 'django.views.defaults.page_not_found'
handler403 = 'django.views.defaults.permission_denied'

sitemaps = {
    'Products': ProductSitemap
}
urlpatterns = patterns('',
    #    Examples:
    #url(r'^$', 'portal.views.home', name='home'),
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^home\.html$', 'products.views.home_view', {'template_name':"home.html"}),
    url(r'^about\.html$', TemplateView.as_view(template_name="about.html")),
    
    url(r'^services\.html$', TemplateView.as_view(template_name="services/index.html")),
    url(r'^services/openerp\.html$', TemplateView.as_view(template_name="services/openerp.html")),
    url(r'^services/consultoria_empresarial\.html$', TemplateView.as_view(template_name="services/consultoria_empresarial.html")),
    url(r'^services/desarrollo_software\.html$', TemplateView.as_view(template_name="services/desarrollo_software.html")),
    url(r'^services/traduccion_subtitulado\.html$', TemplateView.as_view(template_name="services/traduccion_subtitulado.html")),
    url(r'^services/migracion\.html$', TemplateView.as_view(template_name="services/migracion.html")),
    url(r'^services/capacitacion\.html$', TemplateView.as_view(template_name="services/capacitacion.html")),
    url(r'^services/paq-teorico\.html$', TemplateView.as_view(template_name="services/paq-teorico.html")),
    url(r'^services/paq-tecnologico\.html$', TemplateView.as_view(template_name="services/paq-tecnologico.html")),
    url(r'^services/paq-infraestructura\.html$', TemplateView.as_view(template_name="services/paq-infraestructura.html")),
    url(r'^services/identidad_diseno_posicionamiento\.html$', TemplateView.as_view(template_name="services/identidad_diseno_posicionamiento.html")),
    url(r'^contact\.html$', 'products.views.contact_view', {'template_name':"contact.html"}),
    
    url(r'', include('products.urls')),
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/profile/$', TemplateView.as_view(template_name='accounts/profile.html')),
    url(r'^accounts/login_required\.html$', TemplateView.as_view(template_name='accounts/login_required.html')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^profiles/', include('profiles.urls')),
    
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.index', {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^xmlrpc/$', 'django_xmlrpc.views.handle_xmlrpc', name='xmlrpc'),
    
    url(r'^offline/', include('paypal.standard.ipn.urls')),
    url(r'^support/', include('live_support.urls')),
)

urlpatterns += patterns('',
    url(r'^403/$', 'django.views.defaults.permission_denied'),
    url(r'^404/$', 'django.views.defaults.page_not_found'),
#    url(r'^500/$', 'django.views.defaults.server_error'),
)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT})
    )

desarrollo/src/portal/products/urls.py
from django.conf.urls import url, patterns
#from django.views.generic.base import RedirectView

from registration.views import register
from django.contrib.auth import views as auth_views

from django.views.generic.list import ListView
from models import Product
from forms import PortalRegistrationForm

from django_countries.countries import COUNTRIES

from config import portal_config

product_defaults = {'default_url': 'products.html'}

urlpatterns = patterns('',
    url(r'^accounts/register/$',register, {'backend': 'registration.backends.simple.SimpleBackend', 'success_url':"/accounts/profile/", 'form_class': PortalRegistrationForm, 'extra_context':{'countries': COUNTRIES}}),
    url(r'^profiles/edit/$', 'products.views.update_user_profile'),
    url(r'^profiles/password/change/$', auth_views.password_change,{'template_name': 'profiles/password_change.html','post_change_redirect': '/accounts/profile/'},name='auth_password_change'),
    url(r'^profiles/password/reset/$',auth_views.password_reset,{'template_name':'profiles/password_reset.html'},name='auth_password_reset'),
    url(r'^profiles/bonus\.json$', 'products.views.list_profile_bonus', {'template_name': 'profiles/bonus.json'}),
    url(r'^profiles/payments\.json$', 'products.views.list_profile_payments', {'template_name': 'profiles/payments.json'}),
    
    url(r'^products\.html$', ListView.as_view(template_name= 'products/list.html', model = Product)),
    url(r'^products/(?P<slug>\w+)$', 'products.views.products_details_view', {'template_name': 'products/details.html', 'default_url': '/products.html'}),
    url(r'^products/share\.html$', 'products.views.product_share_view', {'template_name': 'products/share.html'}),
    
    url(r'^products/plan_config\.html$', 'products.views.product_config_view', {'template_name': 'products/plan_config.html'}),
    url(r'^products/contract_build\.html$', 'products.views.product_contract_build_view', {'template_name': 'products/contract.html'}),
    url(r'^products/plans\.json$', 'products.views.product_plan_view', {'template_name': 'products/plans.json'}),
    
    url(r'^products/contracts\.json$', 'products.views.list_product_contracts', {'template_name': 'products/contracts.json'}),
    url(r'^products/contract/(?P<contract_id>\d+)/$', 'products.views.product_contract_view', {'template_name': 'products/contract.html'}),
    url(r'^products/contract/cancel\.html$', 'products.views.product_contract_cancel', {'template_name': 'profiles/profile_detail.html'}),
    
    url(r'^products/instances\.json$', 'products.views.list_product_instances', {'template_name': 'products/instances.json'}),
    url(r'^products/instance/(?P<instance_id>\d+)/$', 'products.views.product_instance_view', {'template_name': 'products/instance.html'}),
    url(r'^products/instance/cancel\.html$', 'products.views.product_instance_cancel', {'template_name': 'products/contract.html'}),
    
    url(r'^products/users\.json$', 'products.views.list_product_users', {'template_name': 'products/users.json'}),
    url(r'^products/user/(?P<user_id>\d+)/$', 'products.views.product_user_view', {'template_name': 'products/user.html'}),
    url(r'^products/user/cancel\.html$', 'products.views.product_user_cancel', {'template_name': 'products/instance.html'}),
    url(r'^products/user/password\.html$', 'products.views.product_user_password', {'template_name': 'products/user_password.html'}),
    url(r'^products/user/password/change\.html$', 'products.views.product_user_password_change', {'template_name': 'products/user.html'}),
    
    url(r'^products/contract_demo\.html$', 'products.views.product_demo_view', {'template_name': 'products/contract.html'}),
    
    url(r'^products/pay/(?P<contract_id>\d+)/$', 'products.views.product_contract_pay_view', {'template_name': 'products/pay.html'}),
    
    url(r'^products/return/$', 'products.views.product_return_view', {'template_name': 'products/return.html'}),
    url(r'^products/cancel/$', 'products.views.product_cancel_view', {'template_name': 'products/cancel.html'}),
)

desarrollo/src/portal/social_bookmarking/test_project/urls.py
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/(.*)', admin.site.root),    

    (r'^', include('test_app.urls')),



)

desarrollo/src/portal/products/models.py
from datetime import datetime, timedelta

from django.db import models
from django.contrib.auth.models import User
from django.contrib.comments.moderation import CommentModerator, moderator
from django_countries import CountryField

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    icon = models.ImageField(upload_to="media")
    url_demo = models.URLField()
    url_video = models.URLField()
    modules = models.CharField(max_length=500)
    admin_groups = models.CharField(max_length=500, blank = True, null = True)
    user_groups = models.CharField(max_length=500, blank = True, null = True)
    bonus = models.FloatField()
    bonus_end = models.IntegerField()
    demo_end = models.IntegerField()
    slug = models.SlugField()

    backup = models.FileField(upload_to="products")
    ficha = models.FileField(upload_to="media")
    ppt = models.FileField(upload_to="media")
    manual = models.FileField(upload_to="media")
    src = models.FileField(upload_to="media")
    def get_absolute_url(self):
        return "/products/"+self.slug
        
    def __unicode__(self):
        return self.name



class ProductImage(models.Model):
    image = models.ImageField(upload_to="media")
    product = models.ForeignKey(Product,related_name="images")
        
    def __unicode__(self):
        return self.image.name
    


class ProductPlan(models.Model):
    instances = models.IntegerField()
    users = models.IntegerField()
    product = models.ForeignKey(Product, related_name="plans")
    price = models.FloatField()
    months = models.IntegerField()
        
    def __unicode__(self):
        return u"Instancias: "+str(self.instances)+", Usuarios: "+str(self.users)+", Precio: "+str(self.price)
    


class PortalProfile(models.Model):
    user = models.ForeignKey(User, unique=True)
    country = CountryField()
    phone = models.CharField(max_length= 50)
    pay_excent = models.BooleanField()
#    products = models.O
    
    def get_absolute_url(self):
        return ('profiles_profile_detail', (), { 'username': self.user.username })
    
    get_absolute_url = models.permalink(get_absolute_url)
    
    def get_time_active(self):
        return (datetime.date(datetime.now()) - datetime.date(self.user.date_joined)).days
    
    def __unicode__(self):
        return self.user.username
User.profile = property(lambda u: PortalProfile.objects.get_or_create(user=u)[0])



class ProductContract(models.Model):
    profile = models.ForeignKey(PortalProfile, related_name="contracts")
    product = models.ForeignKey(Product)
    ammount = models.FloatField()
    discount = models.FloatField()
    price = models.FloatField()
    months = models.IntegerField()
    init_date = models.DateTimeField(blank = True, null = True)
    end_date = models.DateTimeField(blank = True, null = True)
    state = models.CharField(max_length = 20, choices = (
        ('draft', 'Borrador'),
        ('demo', 'Prueba'),
        ('active', 'Activo'),
        ('extra', 'Mes Extra'),
        ('cancel', 'Cancelado'),
    ))
    

    
class ProductContractInstance(models.Model):
    contract = models.ForeignKey(ProductContract, related_name="instances")
    db_name = models.CharField(max_length = 250)
    stop_id = models.IntegerField(blank = True, null = True)
    state = models.CharField(max_length = 20, choices = (
        ('draft', 'Borrador'),
        ('active', 'Activo'),
        ('demo', 'Prueba'),
        ('extra', 'Mes Extra'),
        ('cancel', 'Cancelado'),
    ))
    


class ProductContractInstanceUser(models.Model):
    instance = models.ForeignKey(ProductContractInstance, related_name="users")
    username = models.CharField(max_length = 250)
    password = models.CharField(max_length = 64, blank = True, null = True)
    user_id = models.IntegerField(blank = True, null = True)
    state = models.CharField(max_length = 20, choices = (
        ('draft', 'Borrador'),
        ('active', 'Activo'),
        ('cancel', 'Cancelado'),
    ))
    app_admin = models.BooleanField()
    


class ProductContractPayment(models.Model):
    contract = models.ForeignKey(ProductContract, related_name="payments")
    ammount = models.FloatField()
    source = models.CharField(max_length = 250)
    details = models.CharField(max_length = 250)
    pay_date = models.DateTimeField()
    
    
    
class ProfileBonus(models.Model):
    profile = models.ForeignKey(PortalProfile, related_name="bonus")
    product = models.ForeignKey(Product)
    init = models.DateTimeField()
    end = models.DateTimeField()
    active = models.BooleanField()
    


class ProductShare(models.Model):
    email = models.EmailField()
    product = models.ForeignKey(Product)
    profile = models.ForeignKey(PortalProfile)
    active = models.BooleanField()
    

    
class SlideShow(models.Model):
    image = models.ImageField(upload_to="media")
    text = models.TextField()
    link = models.CharField(max_length=250)
    

    
#Contact Coments
class Contact_Entry(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    pub_date = models.DateField()
    enable_comments = models.BooleanField()

class EntryModerator(CommentModerator):
    email_notification = True
    enable_field = 'enable_comments'
moderator.register(Contact_Entry, EntryModerator)

desarrollo/src/portal/social_bookmarking/models.py
from django.db import models

STATUS_CHOICES = (
    (1, 'Inactive'),
    (2, 'Active'),
)

url_help = """
Not a formal URL field. This accepts a string which will have string formatting operations performed on it. Valid key 
mappings for the string formatting includes:
<ul>
  <li><strong>%(url)s</strong> Url to be provided to social bookmarking service</li>
  <li><strong>%(title)s</strong> Title of object being submitted to social bookmarking service</li>  
  <li><strong>%(description)s</strong> Summary or description of the object being submitted</li>    
</ul>
"""

image_help = """
Bookmark image icon stored in media/social_bookmarking/img folder. Stored there so easier to install with fixtures."
"""

js_help = """
Javascript placed here will be inserted in the page in a <script></script> body. Lines will be stripped so make sure that 
you end your lines of code correctly.
"""

class Bookmark(models.Model):
    title           = models.CharField(max_length=255, blank=False)
    status          = models.IntegerField(choices=STATUS_CHOICES, default=2)    
    description     = models.CharField(max_length=255, blank=True, help_text="Because some things want it")
    url             = models.CharField(blank=False, max_length=255, help_text=url_help)
    image           = models.CharField(help_text=image_help, max_length=100, blank=False)
    js              = models.TextField(help_text=js_help, blank=True)
    
    class Meta:
        ordering = ('title',)

    def __unicode__(self):
        return unicode(self.title)

desarrollo/src/portal/paypal/pro/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms

from paypal.pro.fields import CreditCardField, CreditCardExpiryField, CreditCardCVV2Field, CountryField
from paypal.pro.exceptions import PayPalFailure

class PaymentForm(forms.Form):
    """Form used to process direct payments."""
    firstname = forms.CharField(255, label="First Name")
    lastname = forms.CharField(255, label="Last Name")
    street = forms.CharField(255, label="Street Address")
    city = forms.CharField(255, label="City")
    state = forms.CharField(255, label="State")
    countrycode = CountryField(label="Country", initial="US")
    zip = forms.CharField(32, label="Postal / Zip Code")
    acct = CreditCardField(label="Credit Card Number")
    expdate = CreditCardExpiryField(label="Expiration Date")
    cvv2 = CreditCardCVV2Field(label="Card Security Code")

    def process(self, request, item):
        """Process a PayPal direct payment."""
        from paypal.pro.helpers import PayPalWPP
        wpp = PayPalWPP(request) 
        params = self.cleaned_data
        params['creditcardtype'] = self.fields['acct'].card_type
        params['expdate'] = self.cleaned_data['expdate'].strftime("%m%Y")
        params['ipaddress'] = request.META.get("REMOTE_ADDR", "")
        params.update(item)

        try:
            # Create single payment:
            if 'billingperiod' not in params:
                nvp_obj = wpp.doDirectPayment(params)
            # Create recurring payment:
            else:
                nvp_obj = wpp.createRecurringPaymentsProfile(params, direct=True)
        except PayPalFailure:
            return False
        return True

class ConfirmForm(forms.Form):
    """Hidden form used by ExpressPay flow to keep track of payer information."""
    token = forms.CharField(max_length=255, widget=forms.HiddenInput())
    PayerID = forms.CharField(max_length=255, widget=forms.HiddenInput())

desarrollo/src/portal/portal/templates/products/contract.html
	<ul class="breadcrumb">
	    <li><a href="/profiles/{{ user }}/">Perfil</a><span class="divider">/</span></li>
	    <li class="active"><a href="/products/contract/{{ contract.id }}/">Contrato para el Producto {{ contract.product.name }}</a></li>
    </ul>
	<div class="well">
		<h2>Contrato para el Producto {{ contract.product.name }}</h2>
		<center>
			<img src="{{ MEDIA_URL }}{{ contract.product.icon }}" style="height:256px; width:256px;"/>
		</center>
		<hr>
		<form method="POST" action="" id="contract_form" title="Mi Perfil">
			<table>
				<tr>
					<td>
						<table>
							<tr>
								<td><label for="id_name">Nombre:</label></td>
								<td><input class="required" id="id_first_name" value="{{ contract.profile.user.first_name }}" name="first_name" type="text" disabled="disabled"/></td></tr>
							<tr>
							<tr>
								<td><label for="id_username">Nombre de Usuario:</label></td>
								<td><input id="id_username" maxlength="30" value="{{ contract.profile.user.username }}" name="username" type="text" require="true" label="Nombre de Usuario" disabled="disabled"/></td>
							</tr>
							<tr>
								<td><label for="id_email">Correo Electr&oacute;nico:</label></td>
								<td><input id="id_email" name="email" value="{{ contract.profile.user.email }}" type="text" validate="email" require="true" label="E-mail" disabled="disabled"/></td>
							</tr>
							<tr>
								<td><label for="id_date_joined">Inicio del Contrato:</label></td>
								<td><input class="required" id="id_init_date" name="init_date" value="{{ contract.init_date }}" type="text" disabled="disabled"/></td>
							</tr>
							<tr>
								<td><label for="id_state">Estado:</label></td>
								<td><input class="required" id="id_state" name="init_date" value="{{ contract.get_state_display }}" type="text" disabled="disabled"/></td>
							</tr>
							<tr>
								<td><label for="id_price">Precio:</label></td>
								<td><input id="id_price" name="price" value="{{ contract.price }}" type="text" disabled="disabled"/></td>
							</tr>
						</table>
					</td>
					<td>
						<dl style="border-left: 1px solid #EEEEEE; padding: 0 15px">
						<table>
							<tr>
								<td><label for="id_lastname">Apellidos:</label></td>
								<td><input class="required" id="id_last_name" name="last_name" value="{{ contract.profile.user.last_name }}" type="text" disabled="disabled"/></td>
							</tr>
							<tr>
								<td><label for="id_country">Pa&iacute;s:</label></td>
								<td><input class="required" id="id_country" name="country" value="{{ contract.profile.country }}" type="text" disabled="disabled"/></td>
							</tr>
							<tr>
								<td><label for="id_phone">Tel&eacute;fono:</label></td>
								<td><input class="required" id="id_phone" name="phone" value="{{ contract.profile.phone }}" type="text" disabled="disabled"/></td>
							</tr>
							<tr>
								<td><label for="id_date_joined">Fin del Contrato:</label></td>
								<td><input id="id_end_date" name="end_date" value="{{ contract.end_date }}" type="text" disabled="disabled"/></td>
							</tr>
							<tr>
								<td><label for="id_ammount">Cantidad Abonada:</label></td>
								<td><input id="id_ammount" name="ammount" value="{{ contract.ammount }}" type="text" disabled="disabled"/></td>
							</tr>
							<tr>
								<td><label for="id_discount">Descuento:</label></td>
								<td><input id="id_discount" name="discount" value="{{ contract.discount }}" type="text" disabled="disabled"/></td>
							</tr>
						</table>
						</dl>
					</td>
				</tr>
			</table>
			<a class="btn btn-primary" href="/products/plan_buy.html" id="contract_pay"><i class="icon-shopping-cart icon-white"></i>Realizar Pago</a>
			{% if contract.state != 'extra' and contract.state != 'cancel' %}
			<a class="btn" href="#ajax-modal" data-toggle="modal"><i class="icon-ban-circle"></i>Cancelar Contrato</a>
			{% endif %}
			{% if contract.state == 'draft' or contract.state == '' %}
			<a class="btn btn-success" href="/products/contract_demo.html" id="contract_demo"><i class="icon-search"></i>Probar Contrato</a>
			{% endif %}
		</form>
	</div>
	{% if contract.state != 'extra' and contract.state != 'cancel' %}
	<div tabindex="-1" class="modal hide fade" id="ajax-modal" style="display: none; margin-top: -128.5px;" aria-hidden="true">
		<div class="modal-header">
			<button aria-hidden="true" data-dismiss="modal" class="close" type="button">x</button>
			<h4>Confirmaci&oacute;n</h4>
		</div>
		<div class="modal-body" data-replace="true">
			<p>&iquest;Est&aacute; seguro que desea cancelar el Contrato?
		</div>
		<div class="modal-footer">
			<button class="btn btn-primary" id="contract_cancel" >Si</button>
			<button class="btn" data-dismiss="modal" aria-hidden="true">No</button>
		</div>
	</div>
	{% endif %}
	<div class="well">
		<div class="row-fluid">
			<div class="span12">
		    	<div id="grid_container">
		    	</div>
			</div>
		</div>
	</div>

	<script type="text/javascript">
		var token = $.cookie('csrftoken');
		$('#contract_pay').click(function(){
			History.pushState({
	    		state:null, params: {
		    		'csrfmiddlewaretoken': token
		    	}, type: 'post'
			}, null, '/products/pay/{{ contract.id }}/');
			return false;
		});

		$('#grid_container').popover({
			'placement':'bottom',
			'html': true,
			'trigger': 'hover',
			'content': 'Debe seleccionar una instancia para cambiar su configuraci&oacute;n',
			'delay': { show: 500, hide: 100 }
		});

		{% if contract.state != 'extra' and contract.state != 'cancel' %}
		$('#contract_cancel').click(function(){
			$.blockUI({ message: '<h4><img src="{{ STATIC_URL }}img/ajax-loader.gif" /> Cancelando instancia...</h4>'});
			$.ajax({
				type: 'post',
				url: '/products/contract/cancel.html',
				data: {id: '{{ contract.id }}', 'csrfmiddlewaretoken': token},
				success: function(response) {
					$('#ajax-modal').modal("hide");
					$('.center_content').html(response);
				}
			});

			return false;
		});
		{% endif %}
		{% if contract.state == 'draft' or contract.state == '' %}
		$('#contract_demo').click(function(){
			$.blockUI({ message: '<h4><img src="{{ STATIC_URL }}img/ajax-loader.gif" /> Generando instancia de prueba...</h4>'});
			$.ajax({
				type: 'post',
				url: '/products/contract_demo.html',
				data: {id: '{{ contract.id }}', 'csrfmiddlewaretoken': token},
				success: function(response) {
					$.unblockUI();
					$('.center_content').html(response);
				},
				error:function(response) {
					alert('error');
					$.unblockUI();
				}
			});

			return false;
		});
		{% endif %}

		$("#grid_container").datatable({
			title: 'Instancias del Producto',
		    url: '/products/instances.json',
		    post:{
				'csrfmiddlewaretoken': token,
				'id': '{{ contract.id }}'
		    },
		    buttons: [
		    	{ href:"#", id:"editBtn", cls: 'btn-primary', iconCls:"icon-share", label: "Acceso Directo", click: function(e){
		        	var records = $("#grid_container").datatable("getSelected");
		        	if(records.length > 0){
			    		this.href = "{{ url_openerp }}/?app="+records[0].db_name;
			    		this.target='_blank';
		        	} else{
						$('#grid_container').popover('show');
						return false;
					}
			    }},
		        { href:"#", id:"editBtn", cls: 'btn-success', iconCls:"icon-edit", label: "Detalles", click: function(e){
		        	var records = $("#grid_container").datatable("getSelected");
		        	if(records.length > 0){
			    		History.pushState({
				    		state:null, params: {
					    		'csrfmiddlewaretoken': token
					    	}, type: 'post'
						}, null, '/products/instance/'+records[0].id+'/');
		        	} else{
						$('#grid_container').popover('show');
					}
		    		return false;
			    }},
			    { href:"#", id:"editBtn", cls: 'btn', iconCls:"icon-remove", label: "Eliminar", click: function(e){
		        	var records = $("#grid_container").datatable("getSelected");
		        	if(records.length > 0){
			    		History.pushState({
				    		state:null, params: {
				    			'id': records[0].id,
					    		'csrfmiddlewaretoken': token
					    	}, type: 'post'
						}, null, '/products/instance/cancel.html');
		        	} else{
						$('#grid_container').popover('show');
					}
		    		return false;
			    }}
			],
		    showPagination: false,
		    columns: [
				{ title: "", field: "id", hidden: true },
		        { title: "Nombre", sortable: true, field: "db_name", filter: true },
		        { title: "", field: 'link1', css: {width: 30}, callback: function(data, column){
		        	var link = $('<a href="{{ url_openerp }}/?app='+data["db_name"]+'" class="btn btn-mini btn-primary" target="_blank" title="Acceso Directo"><i class="icon-share"/></a>');
		        	return link;
		        }},
		        { title: "", field: 'link2', css: {width: 30}, callback: function(data, column){
		        	var details = $('<a href="/products/instance/'+data["id"]+'/" class="btn btn-mini btn-success" title="Detalles"><i class="icon-edit"/></a>');
		        	details.click(function(){
		        		History.pushState({
				    		state:null, params: {
					    		'csrfmiddlewaretoken': token
					    	}, type: 'post'
						}, null, '/products/instance/'+data["id"]+'/');
		        		return false;
		        	});
		        	return details;
		        }},
		        { title: "", field: 'link3', css: {width: 30}, callback: function(data, column){
		        	var remove = $('<a href="/products/instance/cancel.html" class="btn btn-mini" title="Eliminar"><i class="icon-remove"/></a>');
		        	remove.click(function(){
		        		History.pushState({
				    		state:null, params: {
				    			'id': data["id"],
					    		'csrfmiddlewaretoken': token
					    	}, type: 'post'
						}, null, '/products/instance/cancel.html');
		        		return false;
		        	});
		        	return remove;
		        }}
		    ]
		});

		$('ul.breadcrumb li a').click(function(e) {
			History.pushState({state:null}, null, this.href);
			return false;
		});
	</script>

desarrollo/src/portal/portal/templates/products/pay.html
{% load expr %}
	<div class="well">
		<form action="#" method="post" class="form-horizontal">
			{% csrf_token %}
			<center>
				<img src="{{ MEDIA_URL }}{{ contract.product.icon }}" style="height:256px; width:256px;"/>
			</center>
		    <center>
			    <table>
					<tr>
						<td><label for="id_product">Producto:</label></td>
						<td><input id="id_product" value="{{ contract.product.name }}" name="product" type="text" disabled="disabled"/></td>
						
						<td><label for="id_price">Total a pagar:</label></td>
						<td><input id="id_price" value="{{ price }} USD" name="price" type="text" disabled="disabled"/></td>
					</tr>
					<tr>	
						<td><label for="id_discount">Descuento aplicado:</label></td> 
						<td><input id="id_discount" maxlength="30" value="{% expr contract.discount * 100 %}%" name="discount" type="text" require="true" label="Nombre de Usuario" disabled="disabled"/></td>
						
						<td><label for="id_months">Tiempo a renovar:</label></td> 
						<td><input id="id_months" name="email" value="{{ contract.months }} meses" type="text" require="true" label="months" disabled="disabled"/></td>
					</tr>
				</table>
			</center>
		</form>
		<br>
		<div class="row-fluid">
			<div class="span3"/>
			<div class="span4">
		    	<h4>Pagar Ahora</h4>
		    	{{ form_buy }}
	    	</div>
	    	<div class="span5">
		    	<h4>Subscribir Pago cada {{ contract.months }} Meses</h4>
		    	{{ form_subscribe }}
		    </div>
	    </div>
	</div>